apiVersion: v1
kind: Service
metadata:
  labels:
    app: praeco
  name: praeco
  namespace: sirp
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: praeco
