apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: cortex
  name: cortex
  namespace: sirp
spec:
  ports:
    - name: "9001"
      port: 9001
      targetPort: 9001
  selector:
    app: cortex
