apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cortex-claim1
  namespace: sirp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: thehive-storage
  resources:
    requests:
      storage: 40Gi
