apiVersion: v1
kind: Service
metadata:
  labels:
    app: elastalert
  name: elastalert
  namespace: sirp
spec:
  ports:
    - name: "3030"
      port: 3030
      targetPort: 3030
    - name: "3333"
      port: 3333
      targetPort: 3333
  selector:
    app: elastalert
