apiVersion: v1
kind: Service
metadata:
  name: misp-web
  namespace: sirp
  labels:
    app: misp-web
    # dns: route53
  annotations:
    # domainName: 'changeme'
    # service.beta.kubernetes.io/aws-load-balancer-ssl-cert: 'changeme'
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: '443'
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
spec:
  #type: LoadBalancer
  type: NodePort
  selector:
    app: misp-web
  ports:
    - name: misp-web
      port: 443
      targetPort: 443
      nodePort: 31443
