apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thehive-claim1
  namespace: sirp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: thehive-storage
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thehive-claim2
  namespace: sirp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: thehive-storage
  resources:
    requests:
      storage: 50Gi
