apiVersion: v1
kind: Service
metadata:
  labels:
    app: thehive
  name: thehive
  namespace: sirp
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    app: thehive
