apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: elasticsearch-claim0
  name: elasticsearch-claim0
  namespace: sirp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: thehive-storage
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: elasticsearch-claim1
  name: elasticsearch-claim1
  namespace: sirp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: thehive-storage
  resources:
    requests:
      storage: 400Mi
