apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: sirp
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
    - name: es-node
      port: 9200
      targetPort: 9200
    - name: es-cluster
      port: 9300
      targetPort: 9300
  clusterIP: None
