apiVersion: v1
kind: PersistentVolume
metadata:
  name: db01
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: misp-storage
  hostPath:
    path: /shared/vol02/misp/db01
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: web01
spec:
  capacity:
    storage: 200Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: misp-storage
  hostPath:
    path: /shared/vol02/misp/web01
