apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: cassandra-claim0
  name: cassandra-claim0
  namespace: sirp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: thehive-storage
  resources:
    requests:
      storage: 50Gi
