apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: sirp
  labels:
    app: cassandra
spec:
  selector:
    app: cassandra
  ports:
    - name: intra-node
      port: 7000
      targetPort: 7000
    - name: tls-intra-node
      port: 7001
      targetPort: 7001
    - name: jmx
      port: 7199
      targetPort: 7199
    - name: cql
      port: 9042
      targetPort: 9042
    - name: thrift
      port: 9160
      targetPort: 9160
  clusterIP: None
