apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: nginx-claim0
  name: nginx-claim0
  namespace: sirp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: thehive-storage
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: nginx-claim1
  name: nginx-claim1
  namespace: sirp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: thehive-storage
  resources:
    requests:
      storage: 10Mi
