apiVersion: v1
kind: Service
metadata:
  name: misp-db
  namespace: sirp
  labels:
    app: misp
spec:
  selector:
    app: misp
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  clusterIP: None
